# Generated by Django 3.1.1 on 2020-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_produto_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='core.Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='obs',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
