# Generated by Django 3.1.1 on 2020-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200926_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, to='core.Produto'),
        ),
    ]
